<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: DejaVu Sans, sans-serif; font-size: 12px; color: #1a1a1a; }
  .header { background: #0f172a; color: white; padding: 24px 32px; display: flex; justify-content: space-between; }
  .header h1 { font-size: 22px; font-weight: bold; letter-spacing: 1px; }
  .header .region-badge { background: #10b981; padding: 4px 12px; border-radius: 20px; font-size: 10px; font-weight: bold; }
  .meta { background: #f8fafc; padding: 16px 32px; border-bottom: 2px solid #e2e8f0; display: flex; justify-content: space-between; }
  .meta .label { font-size: 10px; color: #64748b; text-transform: uppercase; letter-spacing: 0.5px; }
  .meta .value { font-size: 13px; font-weight: 600; margin-top: 2px; }
  .section { padding: 24px 32px; }
  .section h2 { font-size: 14px; color: #0f172a; border-bottom: 2px solid #10b981; padding-bottom: 6px; margin-bottom: 16px; text-transform: uppercase; letter-spacing: 0.5px; }
  table { width: 100%; border-collapse: collapse; }
  table thead tr { background: #0f172a; color: white; }
  table thead th { padding: 10px 12px; text-align: left; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; }
  table tbody tr:nth-child(even) { background: #f8fafc; }
  table tbody td { padding: 10px 12px; font-size: 12px; border-bottom: 1px solid #e2e8f0; }
  .total-row td { font-weight: bold; background: #f1f5f9; font-size: 14px; }
  .payment-box { background: #ecfdf5; border: 1px solid #10b981; border-radius: 6px; padding: 16px; margin-top: 16px; }
  .payment-box h3 { color: #065f46; font-size: 12px; margin-bottom: 8px; }
  .footer { background: #f8fafc; padding: 16px 32px; border-top: 2px solid #e2e8f0; font-size: 10px; color: #64748b; margin-top: auto; }
  .footer strong { color: #374151; }
  .two-col { display: flex; gap: 32px; }
  .col { flex: 1; }
</style>
</head>
<body>

<div class="header">
  <div>
    <h1>ECKOX AI PLATFORM</h1>
    <div style="font-size:11px; opacity:0.7; margin-top:4px;">Commercial Quotation</div>
  </div>
  <div style="text-align:right;">
    <div class="region-badge">🌍 AFRICA REGION</div>
    <div style="font-size:11px; margin-top:8px; opacity:0.8;">Ref: {{ $reference }}</div>
    <div style="font-size:11px; opacity:0.8;">{{ $generated_at }}</div>
  </div>
</div>

<div class="meta">
  <div>
    <div class="label">Client Name</div>
    <div class="value">{{ $lead->name }}</div>
  </div>
  <div>
    <div class="label">Email</div>
    <div class="value">{{ $lead->email }}</div>
  </div>
  <div>
    <div class="label">Phone</div>
    <div class="value">{{ $lead->phone ?? 'N/A' }}</div>
  </div>
  <div>
    <div class="label">Valid Until</div>
    <div class="value">{{ now()->addDays(30)->format('d/m/Y') }}</div>
  </div>
</div>

<div class="section">
  <h2>Products & Services</h2>
  <table>
    <thead>
      <tr>
        <th>Description</th>
        <th>Qty</th>
        <th>Unit Price ({{ $currency }})</th>
        <th>Total ({{ $currency }})</th>
      </tr>
    </thead>
    <tbody>
      @foreach($items ?? [] as $item)
      <tr>
        <td>{{ $item['description'] }}</td>
        <td>{{ $item['qty'] ?? 1 }}</td>
        <td>{{ number_format($item['unit_price'], 2) }}</td>
        <td>{{ number_format(($item['qty'] ?? 1) * $item['unit_price'], 2) }}</td>
      </tr>
      @endforeach
      <tr class="total-row">
        <td colspan="3">TOTAL</td>
        <td>{{ $currency }} {{ number_format($total ?? 0, 2) }}</td>
      </tr>
    </tbody>
  </table>

  <div class="payment-box">
    <h3>💳 Payment Information</h3>
    <div><strong>Method:</strong> {{ $payment_method }}</div>
    <div style="margin-top:4px;"><strong>Delivery:</strong> {{ $delivery_days }} business days after payment confirmation</div>
    <div style="margin-top:4px;"><strong>Currency:</strong> {{ $currency }} (US Dollar)</div>
  </div>
</div>

<div class="footer">
  <strong>Legal Notice:</strong> {{ $legal_footer }}<br>
  <span style="margin-top:4px; display:block;">Generated by Eckox AI Platform &bull; Trace ID: {{ $trace_id }}</span>
</div>

</body>
</html>
